version: 2.1

orbs:
  docker: circleci/docker@2.8

executors:
  default:
    docker:
      - image: cimg/base:current-22.04
    working_directory: ~/docker-dev-base

workflows:
  lint:
    jobs:
      - docker/hadolint:
          executor-class: medium
          ignore-rules: DL3059,DL4006
  publish:
    jobs:
      - docker/publish:
          context: dockerhub
          executor: default
          image: verdigristech/dev-base
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
          remote-docker-version: default
          remote-docker-dlc: false
          use-buildkit: true
          use-remote-docker: true
          tag: 11,bullseye
