version: 2.1

orbs:
  docker: circleci/docker@2.1

executors:
  default:
    docker:
      - image: cimg/base:stable-20.04
    working_directory: ~/docker-dev-base

jobs:
  build:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: false
      - docker/check:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
      - docker/publish:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD

workflows:
  version: 2
  lint:
    jobs:
      - docker/hadolint:
          executor-class: medium
          ignore-rules: DL3059
  publish:
    jobs:
      - docker/publish:
          context: dockerhub
          executor: default
          image: verdigristech/dev-base
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
          remote-docker-version: 20.10.14
          use-remote-docker: true
