version: 2.1

orbs:
  docker: circleci/docker@2.8

executors:
  default:
    docker:
      - image: cimg/base:current-22.04
    working_directory: ~/docker-dev-base

jobs:
  publish-image:
    parameters:
      image:
        type: string
        default: verdigristech/dev-base
      tag:
        type: string
        default: latest
    executor: docker/machine
    steps:
      - checkout
      - docker/check:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
      - run:
          name: Create custom builder
          command: |
            docker buildx create --name container-builder --driver docker-container --bootstrap --use
      - docker/build:
          image: << parameters.image >>
          tag: << parameters.tag >>
          use-buildkit: true
          extra_build_args: --platform=linux/amd64,linux/arm64 --push

workflows:
  lint:
    jobs:
      - docker/hadolint:
          executor-class: medium
          ignore-rules: DL3059,DL4006
  publish:
    jobs:
      - publish-image:
          image: verdigristech/dev-base
          tag: 12,bookworm
          context: dockerhub
