version: 2.1

orbs:
  docker: circleci/docker@2.8

executors:
  default:
    docker:
      - image: cimg/base:current-22.04
    working_directory: ~/docker-dev-base

workflows:
  lint:
    jobs:
      - docker/hadolint:
          executor-class: medium
          ignore-rules: DL3059,DL4006
  publish:
    jobs:
      - docker/publish:
          context: dockerhub
          image: verdigristech/dev-base
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
          extra_build_args: --platform=linux/amd64,linux/arm64
          use-buildkit: true
          use-remote-docker: true
          tag: 12,bookworm
